security:
  basic:
    enabled: true
  user:
    name: moclick
    password: 123456

server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://moclick:123456@localhost:8761/eureka
    