spring:
  application:
    name: microservice-consumer-movie-ribbon
server:
  port: 8010
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://moclick:123456@localhost:8761/eureka
  instance: 
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance-id:${server.port}}